"""add phone to customer, year to car

Revision ID: 2937c863b0b3
Revises: 6bb1351d6a4a
Create Date: 2026-07-24 00:49:06.151689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2937c863b0b3'
down_revision: Union[str, Sequence[str], None] = '6bb1351d6a4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cars', sa.Column('year', sa.Integer(), nullable=False))
    op.add_column('customers', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('salesmen', sa.Column('phone', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salesmen', 'phone')
    op.drop_column('customers', 'phone')
    op.drop_column('cars', 'year')
    # ### end Alembic commands ###
